# 1. Each park has a unique name and admission price, as well as a way to read that data
# 2. Each park can list all the vehicles that entered the park
# 3. Each park can list all the passengers that entered the park
# 4. Each park can calculate revenue generated. Revenue is generated by charging the admission price per adult that entered the park.

class Park
    attr_reader :name, :admission_price, :vehicles

    def initialize(name, admission_price)
        @name = name
        @admission_price = admission_price
        @vehicles = []
    end

    def all_vehicles_in_park
        @vehicles
    end

    def add_vehicle(vehicle)
        @vehicles << vehicle
    end

    def all_passengers_in_park
        @vehicles.flat_map do |vehicle|
            vehicle.passengers
        end
    end

    def calculate_revenue
    end
end

